自然言語と単語の分散表示

In [1]:
text = 'You say good bye I say hello.'

In [2]:
text = text.lower()
text = text.replace('.', ' .')
text

'you say good bye i say hello .'

In [4]:
words = text.split(' ')
words

['you', 'say', 'good', 'bye', 'i', 'say', 'hello', '.']

In [5]:
word_to_id = {}
id_to_word = {}

In [6]:
for word in words:
    if word not in word_to_id:
        new_id = len(word_to_id)
        word_to_id[word] = new_id
        id_to_word[new_id] = word

In [7]:
id_to_word

{0: 'you', 1: 'say', 2: 'good', 3: 'bye', 4: 'i', 5: 'hello', 6: '.'}

In [8]:
word_to_id

{'you': 0, 'say': 1, 'good': 2, 'bye': 3, 'i': 4, 'hello': 5, '.': 6}

In [9]:
id_to_word[1]

'say'

In [10]:
word_to_id['hello']

5

In [11]:
import numpy as np

In [13]:
corpus = [word_to_id[w] for w in words]
corpus = np.array(corpus)
corpus

array([0, 1, 2, 3, 4, 1, 5, 6])

In [18]:
def preprocess(text):
    text = text.lower()
    text = text.replace('.', ' .')
    words = text.split(' ')
    
    word_to_id = {}
    id_to_word = {}
    for word in words:
        if word not in word_to_id:
            new_id = len(word_to_id)
            word_to_id[word] = new_id
            id_to_word[new_id] = word
        
    corpus = np.array([word_to_id[w] for w in words])
    
    return corpus, word_to_id, id_to_word

In [19]:
text = 'You say goodbye and I say hello.'

In [20]:
corpus, word_to_id, id_to_word = preprocess(text)

In [21]:
import sys
sys.path.append('..')
# import numpy as np
# from common.util import preprocess

In [30]:
text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)

In [31]:
print(corpus)

[0 1 2 3 4 1 5 6]


In [32]:
print(id_to_word)

{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}


In [33]:
C = np.array([
    [0,1,0,0,0,0,0],
    [1,0,1,0,1,1,0],
    [0,1,0,1,0,0,0],
    [0,0,1,0,1,0,0],
    [0,1,0,1,0,0,0],
    [0,1,0,0,0,0,1],
    [0,0,0,0,0,1,0],
], dtype=np.int32)

In [34]:
print(C[0])

[0 1 0 0 0 0 0]


In [35]:
print(C[4])

[0 1 0 1 0 0 0]


In [36]:
print(C[word_to_id['goodbye']])

[0 1 0 1 0 0 0]


In [37]:
def create_co_matrix(corpus, vocab_size, window_size=1):
    corpus_size = len(corpus)
    co_matrix = np.zeros((vocab_size, vocab_size), dtype=np.int32)
    
    for idx, word_id in enumerate(corpus):
        for i in range(1, window_size + 1):
            left_idx = idx - i
            right_idx = idx + i
            
            if left_idx >= 0:
                left_word_id = corpus[left_idx]
                co_matrix[word_id, left_word_id] += 1
                
            if right_idx <= corpus_size:
                right_word_id = corpus[right_idx]
                co_matrix[word_id, right_word_id] += 1
                
    return co_matrix

In [38]:
def cos_similarity(x, y, eps=le-8):
    nx = x / (np.sqrt(np.sum(x**2)) + eps)
    ny = y / (np.aqrt(np.sum(y**2)) + eps)
    return np.dot(nx, ny)